------------------------------------------------------------------------------------------------------------------------

[2018-11-25 19:50:41 #1 store.file] 
readTextFile error.

[2018-11-25 19:50:41 #2 store.file] 
java.io.FileNotFoundException: C:\Users\Lemmin\.objectdb\exolorer.xml (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.objectdb.o.STH.A(STH.java:717)
	at com.objectdb.o.CNF.<init>(CNF.java:106)
	at com.objectdb.o.CNF.<clinit>(CNF.java:32)
	at com.objectdb.o.MainFrame.init(MainFrame.java:132)
	at com.objectdb.o.EXA.<init>(EXA.java:77)
	at com.objectdb.Explorer$1.run(Explorer.java:57)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

[2018-11-25 19:50:41 #3 store] 
Database 'E:\Dev\Java\Workspace\objectDBjavaFX\db\points.odb' has been recovered (tr. 1-4)

[2018-11-25 19:50:42 #4 store] 
Database 'E:\Dev\Java\Workspace\objectDBjavaFX\db\points.odb' is opened by 6992@DESKTOP-MCTR7T2

[2018-11-25 19:50:42 #5 store] 
Configuration path: E:\University\MIF_Master_Informatics_Semester1\Object Databases\objectdb-2.7.6_01\objectdb.conf

[2018-11-25 19:50:42 #6 store.file] 
readTextFile error.

[2018-11-25 19:50:42 #7 store.file] 
java.io.FileNotFoundException: C:\Users\Lemmin\.objectdb\exolorer.xml (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.objectdb.o.STH.A(STH.java:717)
	at com.objectdb.o.CNF.<init>(CNF.java:106)
	at com.objectdb.o.CNF.f(CNF.java:130)
	at com.objectdb.o.CNC.s(CNC.java:119)
	at com.objectdb.o.EXA.<init>(EXA.java:87)
	at com.objectdb.Explorer$1.run(Explorer.java:57)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

[2018-11-25 19:54:51 #8 store] 
Database 'E:\Dev\Java\Workspace\objectDBjavaFX\db\points.odb' is closed by 6992@DESKTOP-MCTR7T2

[2018-11-25 20:32:21 #9 store] 
Database 'E:\Dev\Java\Workspace\objectDBjavaFX\db\database.odb' has been recovered (tr. 1-7)

[2018-11-25 20:32:21 #10 store] 
Database 'E:\Dev\Java\Workspace\objectDBjavaFX\db\database.odb' is opened by 6992@DESKTOP-MCTR7T2

[2018-11-25 20:32:21 #11 store] 
Configuration path: E:\University\MIF_Master_Informatics_Semester1\Object Databases\objectdb-2.7.6_01\objectdb.conf

[2018-11-25 21:12:06 #12 store] 
Database 'E:\Dev\Java\Workspace\objectDBjavaFX\db\database.odb' is closed by 6992@DESKTOP-MCTR7T2

------------------------------------------------------------------------------------------------------------------------

[2018-11-25 21:16:18 #1 store] 
Database 'E:\Dev\Java\Workspace\objectDBjavaFX\db\database.odb' has been recovered (tr. 1-4)

[2018-11-25 21:16:18 #2 store] 
Database 'E:\Dev\Java\Workspace\objectDBjavaFX\db\database.odb' is opened by 10920@DESKTOP-MCTR7T2

[2018-11-25 21:16:18 #3 store] 
Configuration path: E:\University\MIF_Master_Informatics_Semester1\Object Databases\objectdb-2.7.6_01\objectdb.conf

[2018-11-25 21:17:50 #4 store] 
Database 'E:\Dev\Java\Workspace\objectDBjavaFX\db\database.odb' is closed by 10920@DESKTOP-MCTR7T2

------------------------------------------------------------------------------------------------------------------------

[2018-11-25 21:19:23 #1 explorer] 
[ObjectDB 2.7.6_01] javax.persistence.PersistenceException
Attempt to open a database file 'E:\Dev\Java\Workspace\objectDBjavaFX\db\database.odb' that is currently in use by another process (error 141)
	at com.objectdb.Explorer$1.run(Explorer.java:57)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: com.objectdb.o.UserException: Attempt to open a database file 'E:\Dev\Java\Workspace\objectDBjavaFX\db\database.odb' that is currently in use by another process
	at com.objectdb.o.MSG.a(MSG.java:64)
	at com.objectdb.o.LFL.J(LFL.java:930)
	at com.objectdb.o.LFL.x(LFL.java:887)
	at com.objectdb.o.LFL.x(LFL.java:797)
	at com.objectdb.o.DFL.<init>(DFL.java:241)
	at com.objectdb.o.DMG.<init>(DMG.java:27)
	at com.objectdb.o.MST.<init>(MST.java:127)
	at com.objectdb.o.MST.ao(MST.java:109)
	at com.objectdb.o.MSF.Zw(MSF.java:190)
	at com.objectdb.o.OMF.r(OMF.java:783)
	at com.objectdb.jpa.EMF.r(EMF.java:130)
	at com.objectdb.o.OMF.w(OMF.java:694)
	at com.objectdb.jpa.EMF.createEntityManager(EMF.java:149)
	... 17 more

------------------------------------------------------------------------------------------------------------------------

[2018-11-25 21:19:29 #1 store] 
Database 'E:\Dev\Java\Workspace\objectDBjavaFX\db\database.odb' has been recovered (tr. 1-3)

[2018-11-25 21:19:29 #2 store] 
Database 'E:\Dev\Java\Workspace\objectDBjavaFX\db\database.odb' is opened by 2588@DESKTOP-MCTR7T2

[2018-11-25 21:19:29 #3 store] 
Configuration path: E:\University\MIF_Master_Informatics_Semester1\Object Databases\objectdb-2.7.6_01\objectdb.conf

[2018-11-25 21:21:41 #4 store] 
Database 'E:\Dev\Java\Workspace\objectDBjavaFX\db\database.odb' is closed by 2588@DESKTOP-MCTR7T2

[2018-11-25 21:29:24 #5 explorer] 
[ObjectDB 2.7.6_01] javax.persistence.PersistenceException
Attempt to open a database file 'E:\Dev\Java\Workspace\objectDBjavaFX\db\database.odb' that is currently in use by another process (error 141)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: com.objectdb.o.UserException: Attempt to open a database file 'E:\Dev\Java\Workspace\objectDBjavaFX\db\database.odb' that is currently in use by another process
	at com.objectdb.o.MSG.a(MSG.java:64)
	at com.objectdb.o.LFL.J(LFL.java:930)
	at com.objectdb.o.LFL.x(LFL.java:887)
	at com.objectdb.o.LFL.x(LFL.java:797)
	at com.objectdb.o.DFL.<init>(DFL.java:241)
	at com.objectdb.o.DMG.<init>(DMG.java:27)
	at com.objectdb.o.MST.<init>(MST.java:127)
	at com.objectdb.o.MST.ao(MST.java:109)
	at com.objectdb.o.MSF.Zw(MSF.java:190)
	at com.objectdb.o.OMF.r(OMF.java:783)
	at com.objectdb.jpa.EMF.r(EMF.java:130)
	at com.objectdb.o.OMF.w(OMF.java:694)
	at com.objectdb.jpa.EMF.createEntityManager(EMF.java:149)
	... 40 more

[2018-11-25 21:29:34 #6 store] 
Database 'E:\Dev\Java\Workspace\objectDBjavaFX\db\database.odb' has been recovered (tr. 1-8)

[2018-11-25 21:29:34 #7 store] 
Database 'E:\Dev\Java\Workspace\objectDBjavaFX\db\database.odb' is opened by 2588@DESKTOP-MCTR7T2

[2018-11-25 21:29:34 #8 store] 
Configuration path: E:\University\MIF_Master_Informatics_Semester1\Object Databases\objectdb-2.7.6_01\objectdb.conf

------------------------------------------------------------------------------------------------------------------------

[2018-11-25 21:55:45 #1 store] 
Database 'E:\Dev\Java\Workspace\objectDBjavaFX\db\database.odb' has been recovered (tr. 1-8)

[2018-11-25 21:55:46 #2 store] 
Database 'E:\Dev\Java\Workspace\objectDBjavaFX\db\database.odb' is opened by 14460@DESKTOP-MCTR7T2

[2018-11-25 21:55:46 #3 store] 
Configuration path: E:\University\MIF_Master_Informatics_Semester1\Object Databases\objectdb-2.7.6_01\objectdb.conf

[2018-11-25 21:56:06 #4 store] 
Database 'E:\Dev\Java\Workspace\objectDBjavaFX\db\database.odb' is closed by 14460@DESKTOP-MCTR7T2

------------------------------------------------------------------------------------------------------------------------

[2018-11-25 21:56:28 #1 server] 
Server on port 6136 has started by 16272@DESKTOP-MCTR7T2

------------------------------------------------------------------------------------------------------------------------

[2018-11-25 21:57:04 #1 store] 
Database 'E:\Dev\Java\Workspace\objectDBjavaFX\db\database.odb' is opened by 13884@DESKTOP-MCTR7T2

[2018-11-25 21:57:04 #2 store] 
Configuration path: E:\University\MIF_Master_Informatics_Semester1\Object Databases\objectdb-2.7.6_01\objectdb.conf

[2018-11-25 21:57:24 #3 store] 
Database 'E:\Dev\Java\Workspace\objectDBjavaFX\db\database.odb' is closed by 13884@DESKTOP-MCTR7T2

[2018-11-25 21:58:13 #4 explorer] 
[ObjectDB 2.7.6_01] javax.persistence.PersistenceException
Failed to open file 'E:\University\MIF_Master_Informatics_Semester1\Object Databases\objectdb-2.7.6_01\db' (error 115)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: com.objectdb.o.UserException: Failed to open file 'E:\University\MIF_Master_Informatics_Semester1\Object Databases\objectdb-2.7.6_01\db'
	at com.objectdb.o.MSG.a(MSG.java:77)
	at com.objectdb.o.LFL.t(LFL.java:1488)
	at com.objectdb.o.LFL.x(LFL.java:901)
	at com.objectdb.o.LFL.x(LFL.java:797)
	at com.objectdb.o.DFL.<init>(DFL.java:241)
	at com.objectdb.o.DMG.<init>(DMG.java:27)
	at com.objectdb.o.MST.<init>(MST.java:127)
	at com.objectdb.o.MST.ao(MST.java:109)
	at com.objectdb.o.MSF.Zw(MSF.java:190)
	at com.objectdb.o.OMF.r(OMF.java:783)
	at com.objectdb.jpa.EMF.r(EMF.java:130)
	at com.objectdb.o.OMF.w(OMF.java:694)
	at com.objectdb.jpa.EMF.createEntityManager(EMF.java:149)
	... 18 more
Caused by: java.io.FileNotFoundException: E:\University\MIF_Master_Informatics_Semester1\Object Databases\objectdb-2.7.6_01\db (Access is denied)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(Unknown Source)
	at java.io.RandomAccessFile.<init>(Unknown Source)
	at com.objectdb.o.LFL.x(LFL.java:884)
	... 28 more

[2018-11-25 21:58:51 #5 store] 
Database 'E:\University\MIF_Master_Informatics_Semester1\Object Databases\objectdb-2.7.6_01\db\world.odb' is opened by 13884@DESKTOP-MCTR7T2

[2018-11-25 21:58:51 #6 store] 
Configuration path: E:\University\MIF_Master_Informatics_Semester1\Object Databases\objectdb-2.7.6_01\objectdb.conf

[2018-11-25 22:13:05 #7 store] 
Database 'E:\University\MIF_Master_Informatics_Semester1\Object Databases\objectdb-2.7.6_01\db\world.odb' is closed by 13884@DESKTOP-MCTR7T2

------------------------------------------------------------------------------------------------------------------------

[2018-11-25 22:38:53 #1 store] 
Database 'E:\University\MIF_Master_Informatics_Semester1\Object Databases\program\points-console\movie2.odb' is opened by 8440@DESKTOP-MCTR7T2

[2018-11-25 22:38:53 #2 store] 
Configuration path: E:\University\MIF_Master_Informatics_Semester1\Object Databases\objectdb-2.7.6_01\objectdb.conf

[2018-11-25 22:45:26 #3 store] 
Database 'E:\University\MIF_Master_Informatics_Semester1\Object Databases\program\points-console\movie2.odb' is closed by 8440@DESKTOP-MCTR7T2

------------------------------------------------------------------------------------------------------------------------

[2018-11-25 23:19:48 #1 store] 
Database 'E:\Dev\Java\Workspace\objectDBjavaFX\db\database.odb' has been recovered (tr. 1-8)

[2018-11-25 23:19:48 #2 store] 
Database 'E:\Dev\Java\Workspace\objectDBjavaFX\db\database.odb' is opened by 5140@DESKTOP-MCTR7T2

[2018-11-25 23:19:48 #3 store] 
Configuration path: E:\University\MIF_Master_Informatics_Semester1\Object Databases\objectdb-2.7.6_01\objectdb.conf

[2018-11-25 23:19:54 #2 server] 
Server on port 6136 has stopped by 16272@DESKTOP-MCTR7T2

[2018-11-25 23:22:35 #4 store] 
Database 'E:\Dev\Java\Workspace\objectDBjavaFX\db\database.odb' is closed by 5140@DESKTOP-MCTR7T2

------------------------------------------------------------------------------------------------------------------------

[2018-11-25 23:42:44 #1 store] 
Database 'E:\Dev\Java\Workspace\objectDBjavaFX\db\database.odb' has been recovered (tr. 1-8)

[2018-11-25 23:42:45 #2 store] 
Database 'E:\Dev\Java\Workspace\objectDBjavaFX\db\database.odb' is opened by 15560@DESKTOP-MCTR7T2

[2018-11-25 23:42:45 #3 store] 
Configuration path: E:\University\MIF_Master_Informatics_Semester1\Object Databases\objectdb-2.7.6_01\objectdb.conf

[2018-11-25 23:48:05 #4 store] 
Database 'E:\Dev\Java\Workspace\objectDBjavaFX\db\database.odb' is closed by 15560@DESKTOP-MCTR7T2

